export default [
  `Vous savez la différence entre pylon et l'oxygène ? Bah on a besoin d'oxygène`,
  `Pylon supporte le Biarritz Olympique`,
  `Pylon a un autographe de Francis Lalanne`,
  `Pylon n'aime pas Céline Dion`,
  `Pylon n'a même pas de repo Github`,
  `Pylon ? Il ne parle pas de saucisse et il n'est pas drôle`,
  `On peut arrêter de parler de lui ? Ca devient génant`,
  `Windows a annoncé une mise à jour de Pylon avec la sortie de Windows 14`,
  `Les extra-terrestres ont envahi la terre, puis ils ont rencontré Pylon. On les a jamais revus.`,
  `Pylon porte des chaussettes avec ses sandales`,
  `Pylon ? Connais pas.`,
  `Pylon, t'es comme le H de Hawaï... Tu sers à rien !`,
  `Vous aviez remarqué que Pylon, en rébus, c'était encore plus ridicule ?`,
  `On dit souvent aux jeunes bots : Ecoute bien en cours, sinon tu finiras comme Pylon`,
  `Un jour Pylon sauvera le monde. Mais pas aujourd'hui. Ni demain d'ailleurs`,
  `Pylon il a formé les employés de la poste`,
  `Pylon regarde ses films sur Dailymotion`,
  `Pylon a été codé sur WebDev`,
  `Pylon vote Zemmour, enfin c'est ce qu'on m'a dit`,
  `Le seul bot plus bête que Pylon, c'est Pylon2`,
];
